### ISSUE TITLE
LogFox not displaying new logs

### ISSUE THREAD

**Issue by 2011** [F0x1d/LogFox#110]
Environment: LogFox 1.5.6 running on a 905X3 television box with a custom ROM based on Android 9.

Started LogFox, and searched for a specific application that kept crashing. Eventually, I wanted to look at other things, I cleared the logs, but every time I go back into LogFox, I see two of the lines from two days ago, literally repeated (same timestamps) for hundreds of pages. I have tried force stopping the app, stopping the service, restaring logging, and everything else I can think of, but no matter what I try, when I start LogFox, I see nothing but those same two line from two days ago repeated for hundreds of pages.

The log for LogFox has nothing interesting (literally just "Start proc," but I do have a screenshot (although you can't see the incredibly small scroll bar on the right in it).

![logfox](https://github.com/F0x1d/LogFox/assets/550150/f49b4073-442a-463c-bf9b-9f9f03c2b615)

Any suggestions? Thank you in advance.

As a side request, could you add "Save" to "Copy," "Share," and "Zip" in the page that displays crashes?

**Comment by 2011** [comment]
> Which backend are you using (default, root, shizuku)?

I have never changed anything, and just verifiend that I do have "Default" selected. Does root work better (I could potentially change to that backend)?

> If **default** - try to run `logcat` in terminal emulator and check if it also logs only these 2 lines

Looks normal (60,000+ lines ending with the events of a few seconds ago).

Ahhhhh! The very beginning of the logcat output consists of these three lines (had to use "less" to see that):

```
--------- beginning of crash
03-03 18:37:33.000  4306  4306 E AndroidRuntime: FATAL EXCEPTION: main
03-03 18:37:33.000  4306  4306 E AndroidRuntime: Process: org.pocketworkstation.pckeyboard, PID: 4306
```

That doesn't seem coincidental.

**Comment by F0x1d** [comment]
Can you provide an output of the latest lines from logcat?

**Comment by 2011** [comment]
> Can you provide an output of the latest lines from logcat?

Looks normal to me (but I have a relatively low level of expertise in this area):

```
03-05 21:23:52.252  1287  1287 I cat     : type=1400 audit(0.0:8734): avc: denied { write } for path="pipe:[648227679]" dev="pipefs" ino=648227679 scontext=u:r:toolbox:s0 tcontext=u:r:init:s0 tclass=fifo_file permissive=1
03-05 21:23:52.252  1288  1288 I sed     : type=1400 audit(0.0:8735): avc: denied { read } for path="pipe:[648227679]" dev="pipefs" ino=648227679 scontext=u:r:toolbox:s0 tcontext=u:r:init:s0 tclass=fifo_file permissive=1
03-05 21:23:52.276  1288  1288 I sed     : type=1400 audit(0.0:8736): avc: denied { getattr } for path="pipe:[648227679]" dev="pipefs" ino=648227679 scontext=u:r:toolbox:s0 tcontext=u:r:init:s0 tclass=fifo_file permissive=1
03-05 21:24:12.568  3636  3646 I system_server: Background concurrent copying GC freed 66230(4MB) AllocSpace objects, 205(4MB) LOS objects, 42% free, 11MB/19MB, paused 268us total 139.515ms
03-05 21:24:35.539  3480  3549 E storaged: getDiskStats failed with result NOT_SUPPORTED and size 0
03-05 21:24:45.306  3636  9144 D WificondControl: Scan result ready event
03-05 21:24:45.309  3636  3659 I EthernetTracker: interfaceLinkStateChanged, iface: wlan0, up: true
03-05 21:24:52.301  3636  3646 I system_server: Background concurrent copying GC freed 70294(4MB) AllocSpace objects, 198(3MB) LOS objects, 42% free, 11MB/19MB, paused 213us total 161.139ms
03-05 21:25:34.304  3636  3646 I system_server: Background concurrent copying GC freed 72439(4MB) AllocSpace objects, 210(4MB) LOS objects, 42% free, 11MB/19MB, paused 200us total 155.367ms
03-05 21:25:35.539  3480  3549 E storaged: getDiskStats failed with result NOT_SUPPORTED and size 0
03-05 21:26:15.453  3636  3646 I system_server: Background concurrent copying GC freed 66371(4MB) AllocSpace objects, 207(4MB) LOS objects, 42% free, 11MB/19MB, paused 203us total 129.406ms
03-05 21:26:35.540  3480  3549 E storaged: getDiskStats failed with result NOT_SUPPORTED and size 0
03-05 21:26:43.152  3636  3636 I Timer-0 : type=1400 audit(0.0:8737): avc: denied { read } for name="temp" dev="sysfs" ino=11024 scontext=u:r:system_server:s0 tcontext=u:object_r:sysfs:s0 tclass=file permissive=1
03-05 21:26:43.152  3636  3636 I Timer-0 : type=1400 audit(0.0:8738): avc: denied { open } for path="/sys/devices/virtual/thermal/thermal_zone0/temp" dev="sysfs" ino=11024 scontext=u:r:system_server:s0 tcontext=u:object_r:sysfs:s0 tclass=file permissive=1
03-05 21:26:54.472  4810  4810 I cat     : type=1400 audit(0.0:8739): avc: denied { read } for name="wake_lock" dev="sysfs" ino=3699 scontext=u:r:toolbox:s0 tcontext=u:object_r:sysfs_wake_lock:s0 tclass=file permissive=1
03-05 21:26:56.315  3636  3646 I system_server: Background concurrent copying GC freed 66556(4MB) AllocSpace objects, 202(3MB) LOS objects, 42% free, 11MB/19MB, paused 237us total 152.426ms
```

**Comment by F0x1d** [comment]
What about output from `logcat -v uid -v epoch`?

**Comment by 2011** [comment]
> What about output from `logcat -v uid -v epoch`?

Don't know how much output you want, so I will give you the last 30+ lines:

```
         1709654818.937 10077  6595 12179 I om.f0x1d.logfo: Clamp target GC heap from 262MB to 256MB
         1709654818.937 10077  6595 12767 I om.f0x1d.logfo: WaitForGcToComplete blocked Alloc on HeapTrim for 1.598s
         1709654818.937 10077  6595 12767 I om.f0x1d.logfo: Starting a blocking GC Alloc
         1709654818.937 10077  6595 15968 I om.f0x1d.logfo: WaitForGcToComplete blocked Alloc on HeapTrim for 1.579s
         1709654818.937 10077  6595 15968 I om.f0x1d.logfo: Starting a blocking GC Alloc
         1709654818.938 10077  6595 16317 I om.f0x1d.logfo: Starting a blocking GC Alloc
         1709654818.938 10077  6595 16317 I om.f0x1d.logfo: Starting a blocking GC Alloc
         1709654819.247 10077  6595 12767 I om.f0x1d.logfo: Waiting for a blocking GC Alloc
         1709654820.587 10077  6595 16317 I om.f0x1d.logfo: Clamp target GC heap from 262MB to 256MB
         1709654820.588 10077  6595 12767 I om.f0x1d.logfo: WaitForGcToComplete blocked Alloc on HeapTrim for 1.340s
         1709654820.588 10077  6595 12767 I om.f0x1d.logfo: Starting a blocking GC Alloc
         1709654820.596 10077  6595 14083 I om.f0x1d.logfo: Starting a blocking GC Alloc
         1709654820.596 10077  6595 14083 I om.f0x1d.logfo: Starting a blocking GC Alloc
         1709654820.598 10077  6595 28018 I om.f0x1d.logfo: Waiting for a blocking GC Alloc
         1709654820.616 10077  6595 15968 I om.f0x1d.logfo: Waiting for a blocking GC Alloc
         1709654822.259 10077  6595 14083 I om.f0x1d.logfo: Clamp target GC heap from 262MB to 256MB
         1709654822.259 10077  6595 28018 I om.f0x1d.logfo: WaitForGcToComplete blocked Alloc on HeapTrim for 1.660s
         1709654822.259 10077  6595 28018 I om.f0x1d.logfo: Starting a blocking GC Alloc
         1709654822.259 10077  6595  6607 I om.f0x1d.logfo: WaitForGcToComplete blocked HeapTrim on HeapTrim for 1.649s
         1709654822.260 10077  6595 15968 I om.f0x1d.logfo: Waiting for a blocking GC Alloc
         1709654822.260 10077  6595 15968 I om.f0x1d.logfo: WaitForGcToComplete blocked Alloc on HeapTrim for 1.643s
         1709654822.260 10077  6595 15968 I om.f0x1d.logfo: Starting a blocking GC Alloc
         1709654822.268 10077  6595 16326 I om.f0x1d.logfo: Starting a blocking GC Alloc
         1709654822.268 10077  6595 16326 I om.f0x1d.logfo: Starting a blocking GC Alloc
         1709654822.688 10077  6595 15968 I om.f0x1d.logfo: Waiting for a blocking GC Alloc
         1709654824.065 10077  6595 16326 I om.f0x1d.logfo: Clamp target GC heap from 262MB to 256MB
         1709654824.066 10077  6595 15968 I om.f0x1d.logfo: WaitForGcToComplete blocked Alloc on HeapTrim for 1.377s
         1709654824.066 10077  6595 15968 I om.f0x1d.logfo: Starting a blocking GC Alloc
         1709654821.124  logd 16321 16321 I cat     : type=1400 audit(0.0:9010): avc: denied { read } for name="wake_lock" dev="sysfs" ino=3699 scontext=u:r:toolbox:s0 tcontext=u:object_r:sysfs_wake_lock:s0 tclass=file permissive=1
         1709654821.124  logd 16321 16321 I cat     : type=1400 audit(0.0:9011): avc: denied { open } for path="/sys/power/wake_lock" dev="sysfs" ino=3699 scontext=u:r:toolbox:s0 tcontext=u:object_r:sysfs_wake_lock:s0 tclass=file permissive=1
         1709654824.074 10077  6595 12179 I om.f0x1d.logfo: Starting a blocking GC Alloc
         1709654824.074 10077  6595 12179 I om.f0x1d.logfo: Starting a blocking GC Alloc
         1709654824.077 10077  6595 12314 I om.f0x1d.logfo: Waiting for a blocking GC Alloc
```

**Comment by F0x1d** [comment]
Do you have enabled "Show only logs from app start"? If no, then can you provide the lines from `logcat -v uid -v epoch` which appear after these 2. So, I guess the problem is in the third line then, can you provide 0-10 of first lines?

**Comment by 2011** [comment]
> Do you have enabled "Show only logs from app start"? If no, then can you provide the lines from `logcat -v uid -v epoch` which appear after these 2? I guess the problem is in the third line then, so can you provide 0-10 of first lines?

I do not have "Show only logs which have appeared since the app launch" enabled.

The output of the command you gave:

```
--------- beginning of crash
         1709444253.000 10081  4306  4306 E AndroidRuntime: FATAL EXCEPTION: main
         1709444253.000 10081  4306  4306 E AndroidRuntime: Process: org.pocketworkstation.pckeyboard, PID: 4306
         1709444253.000 10081  4306  4306 E AndroidRuntime: java.lang.RuntimeException: Unable to create service org.pocketworkstation.pckeyboard.LatinIME: java.lang.SecurityException: Failed to find provider user_dictionary for user 0; expected to find a valid ContentProvider for this authority
         1709444253.000 10081  4306  4306 E AndroidRuntime:     at android.app.ActivityThread.handleCreateService(ActivityThread.java:3544)
         1709444253.000 10081  4306  4306 E AndroidRuntime:     at android.app.ActivityThread.access$1300(ActivityThread.java:199)
         1709444253.000 10081  4306  4306 E AndroidRuntime:     at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1666)
         1709444253.000 10081  4306  4306 E AndroidRuntime:     at android.os.Handler.dispatchMessage(Handler.java:106)
         1709444253.000 10081  4306  4306 E AndroidRuntime:     at android.os.Looper.loop(Looper.java:193)
         1709444253.000 10081  4306  4306 E AndroidRuntime:     at android.app.ActivityThread.main(ActivityThread.java:6669)
         1709444253.000 10081  4306  4306 E AndroidRuntime:     at java.lang.reflect.Method.invoke(Native Method)
         1709444253.000 10081  4306  4306 E AndroidRuntime:     at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
         1709444253.000 10081  4306  4306 E AndroidRuntime:     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858)
         1709444253.000 10081  4306  4306 E AndroidRuntime: Caused by: java.lang.SecurityException: Failed to find provider user_dictionary for user 0; expected to find a valid ContentProvider for this authority
```

**Comment by 2011** [comment]
> Does LogFox work if you switch this function on?

Yes, that does show the latest log entries now. :) With that function off, LogFox remains stuck on log entriest from nine days ago.

**Comment by F0x1d** [comment]
tbh, I can't really find the reason for this behaviour. Maybe you can contact me in [Telegram](https://t.me/f0x1d) to speed up this bugfix?

**Comment by F0x1d** [comment]
No updates on here, can't reproduce. Reopen if still actual on v2.0.0
