### ISSUE TITLE
java.util.concurrent.TimeoutException

### ISSUE THREAD

**Issue by dxuser114** [F0x1d/LogFox#115]
OS:Android 11 API 30
Version:1.5.7
FATAL EXCEPTION: FinalizerWatchdogDaemon
Process: com.f0x1d.logfox, PID: 28224
java.util.concurrent.TimeoutException: com.android.internal.os.BinderInternal$GcWatcher.finalize() timed out after 10 seconds
	at java.lang.Object.wait(Native Method)
	at java.lang.Object.wait(Object.java:442)
	at java.lang.ref.ReferenceQueue.remove(ReferenceQueue.java:190)
	at java.lang.ref.ReferenceQueue.remove(ReferenceQueue.java:211)
	at java.lang.Daemons$FinalizerDaemon.runInternal(Daemons.java:273)
	at java.lang.Daemons$Daemon.run(Daemons.java:139)
	at java.lang.Thread.run(Thread.java:923)

**Comment by F0x1d** [comment]
Any additional info? Device, OS, backend, steps to reproduce?

**Comment by F0x1d** [comment]
Should be fixed in v2.0.0
