### ISSUE TITLE
Crash : java.lang.RuntimeException: android.os.TransactionTooLargeException: data parcel size 1482336 bytes

### ISSUE THREAD

**Issue by Massedil** [F0x1d/LogFox#120]
Reproduce :
- Select all logs (10000 items)
- In the menu, choose "copy"

Device : 
- Samsung Galaxy A52s / LineageOS 21.0 / Android 14

```
FATAL EXCEPTION: main
Process: com.f0x1d.logfox, PID: 3857
java.lang.RuntimeException: android.os.TransactionTooLargeException: data parcel size 1482336 bytes
at android.content.ClipboardManager.setPrimaryClip(ClipboardManager.java:189)
at f3.a.d(SourceFile:1)
at e4.d.a(SourceFile:155)
at e4.d.k(SourceFile:28)
at i3.a.onMenuItemClick(SourceFile:13)
at k.o.q(SourceFile:19)
at k.x.onItemClick(SourceFile:41)
at android.widget.AdapterView.performItemClick(AdapterView.java:330)
at android.widget.AbsListView.performItemClick(AbsListView.java:1265)
at android.widget.AbsListView$PerformClick.run(AbsListView.java:3278)
at android.widget.AbsListView$3.run(AbsListView.java:4244)
at android.os.Handler.handleCallback(Handler.java:958)
at android.os.Handler.dispatchMessage(Handler.java:99)
at android.os.Looper.loopOnce(Looper.java:205)
at android.os.Looper.loop(Looper.java:294)
at android.app.ActivityThread.main(ActivityThread.java:8248)
at java.lang.reflect.Method.invoke(Native Method)
at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:552)
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:971)
Caused by: android.os.TransactionTooLargeException: data parcel size 1482336 bytes
at android.os.BinderProxy.transactNative(Native Method)
at android.os.BinderProxy.transact(BinderProxy.java:584)
at android.content.IClipboard$Stub$Proxy.setPrimaryClip(IClipboard.java:389)
at android.content.ClipboardManager.setPrimaryClip(ClipboardManager.java:182)
... 18 more
```

**Comment by F0x1d** [comment]
Fixed in v2.0.0
