### ISSUE TITLE
Filter Crash

### ISSUE THREAD

**Issue by TakenMC** [F0x1d/LogFox#151]
Every time I would try and create a loglevel filter it would crash the app

I would get this crash log from the app

```
FATAL EXCEPTION: main
Process: com.f0x1d.logfox, PID: 9575
java.lang.ArrayIndexOutOfBoundsException: length=0; index=0
	at j.a.getView(SourceFile:11)
	at android.widget.AbsListView.obtainView(AbsListView.java:2709)
	at android.widget.ListView.measureHeightOfChildren(ListView.java:1461)
	at android.widget.ListView.onMeasure(ListView.java:1367)
	at android.view.View.measure(View.java:28588)
	at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:7442)
	at android.widget.FrameLayout.onMeasure(FrameLayout.java:194)
	at android.view.View.measure(View.java:28588)
	at androidx.appcompat.widget.AlertDialogLayout.onMeasure(SourceFile:151)
	at android.view.View.measure(View.java:28588)
	at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:7442)
	at android.widget.FrameLayout.onMeasure(FrameLayout.java:194)
	at androidx.appcompat.widget.ContentFrameLayout.onMeasure(SourceFile:160)
	at android.view.View.measure(View.java:28588)
	at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:7442)
	at android.widget.FrameLayout.onMeasure(FrameLayout.java:194)
	at android.view.View.measure(View.java:28588)
	at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:7442)
	at android.widget.FrameLayout.onMeasure(FrameLayout.java:194)
	at android.view.View.measure(View.java:28588)
	at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:7442)
	at android.widget.LinearLayout.measureChildBeforeLayout(LinearLayout.java:1608)
	at android.widget.LinearLayout.measureVertical(LinearLayout.java:878)
	at android.widget.LinearLayout.onMeasure(LinearLayout.java:721)
	at android.view.View.measure(View.java:28588)
	at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:7442)
	at android.widget.FrameLayout.onMeasure(FrameLayout.java:194)
	at com.android.internal.policy.DecorView.onMeasure(DecorView.java:1054)
	at android.view.View.measure(View.java:28588)
	at android.view.ViewRootImpl.performMeasure(ViewRootImpl.java:5273)
	at android.view.ViewRootImpl.measureHierarchy(ViewRootImpl.java:3629)
	at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:4030)
	at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:3345)
	at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:11437)
	at android.view.Choreographer$CallbackRecord.run(Choreographer.java:1690)
	at android.view.Choreographer$CallbackRecord.run(Choreographer.java:1699)
	at android.view.Choreographer.doCallbacks(Choreographer.java:1154)
	at android.view.Choreographer.doFrame(Choreographer.java:1080)
	at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:1647)
	at android.os.Handler.handleCallback(Handler.java:958)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loopOnce(Looper.java:230)
	at android.os.Looper.loop(Looper.java:319)
	at android.app.ActivityThread.main(ActivityThread.java:9063)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:588)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1103)
```

**Comment by F0x1d** [comment]
will be fixed in next version
