### ISSUE TITLE
Crash:when adding apps to filters

### ISSUE THREAD

**Issue by HusniMuhammad** [F0x1d/LogFox#155]
```FATAL EXCEPTION: main
Process: com.f0x1d.logfox, PID: 22257
java.lang.ArrayIndexOutOfBoundsException: length=0; index=0
	at j.a.getView(SourceFile:11)
	at android.widget.AbsListView.obtainView(AbsListView.java:2387)
	at android.widget.ListView.measureHeightOfChildren(ListView.java:1417)
	at android.widget.ListView.onMeasure(ListView.java:1323)
	at android.view.View.measure(View.java:25589)
	at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:7020)
	at android.widget.FrameLayout.onMeasure(FrameLayout.java:194)
	at android.view.View.measure(View.java:25589)
	at androidx.appcompat.widget.AlertDialogLayout.onMeasure(SourceFile:151)
	at android.view.View.measure(View.java:25589)
	at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:7020)
	at android.widget.FrameLayout.onMeasure(FrameLayout.java:194)
	at androidx.appcompat.widget.ContentFrameLayout.onMeasure(SourceFile:160)
	at android.view.View.measure(View.java:25589)
	at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:7020)
	at android.widget.FrameLayout.onMeasure(FrameLayout.java:194)
	at android.view.View.measure(View.java:25589)
	at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:7020)
	at android.widget.FrameLayout.onMeasure(FrameLayout.java:194)
	at android.view.View.measure(View.java:25589)
	at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:7020)
	at android.widget.LinearLayout.measureChildBeforeLayout(LinearLayout.java:1552)
	at android.widget.LinearLayout.measureVertical(LinearLayout.java:842)
	at android.widget.LinearLayout.onMeasure(LinearLayout.java:721)
	at android.view.View.measure(View.java:25589)
	at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:7020)
	at android.widget.FrameLayout.onMeasure(FrameLayout.java:194)
	at com.android.internal.policy.DecorView.onMeasure(DecorView.java:750)
	at android.view.View.measure(View.java:25589)
	at android.view.ViewRootImpl.performMeasure(ViewRootImpl.java:3468)
	at android.view.ViewRootImpl.measureHierarchy(ViewRootImpl.java:2272)
	at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:2557)
	at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:2023)
	at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:8314)
	at android.view.Choreographer$CallbackRecord.run(Choreographer.java:972)
	at android.view.Choreographer.doCallbacks(Choreographer.java:796)
	at android.view.Choreographer.doFrame(Choreographer.java:731)
	at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:957)
	at android.os.Handler.handleCallback(Handler.java:938)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loop(Looper.java:223)
	at android.app.ActivityThread.main(ActivityThread.java:7948)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:603)
	at `com.android.internal.os.ZygoteInit.main(ZygoteInit.java:947)```

**Comment by F0x1d** [comment]
Any additional info?

**Comment by HusniMuhammad** [comment]
`Android version:11
Kernel build information:Linux localhost 4.14.193+-ab478 #1 SMP PREEMPT Thu May 9 16:42:40 CST 2024 armv8l Android
Device manufacturer:realme
Device model:RMX3231
`

**Comment by HusniMuhammad** [comment]
> Any additional info?

Here's the screen record 
https://github.com/user-attachments/assets/7deee0d9-7164-4fe8-8ee7-d7741bc0780e

**Comment by F0x1d** [comment]
Will be fixed in next version
