### ISSUE TITLE
During fatal exception, logs are collected but not fully? 

### ISSUE THREAD

**Issue by r3538987** [F0x1d/LogFox#157]
When crashes are caught or recorded, in exception section there part which says: **_... XX more_** lines
Which leads me think that such maybe there is useful info further, but that part is not available.

- Is this intended, or there are workarounds to get entire part? 
- Or usually for debugging purposes first section is enough to track down problematic spot? 

```FATAL EXCEPTION: main
Process: reddit.news, PID: 24945
java.lang.RuntimeException: Unable to start activity ComponentInfo{reddit.news/reddit.news.RedditNavigation}: java.lang.ClassCastException: android.app.Application cannot be cast to reddit.news.RelayApplication
	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:4169)
	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:4325)
	at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:101)
	at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135)
	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2574)
	at android.os.Handler.dispatchMessage(Handler.java:106)
	at android.os.Looper.loopOnce(Looper.java:226)
	at android.os.Looper.loop(Looper.java:313)
	at android.app.ActivityThread.main(ActivityThread.java:8762)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:604)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1067)
Caused by: java.lang.ClassCastException: android.app.Application cannot be cast to reddit.news.RelayApplication
	at reddit.news.RelayApplication.a(RelayApplication.java:7)
	at reddit.news.RedditNavigation.onCreate(RedditNavigation.java:44)
	at android.app.Activity.performCreate(Activity.java:8591)
	at android.app.Activity.performCreate(Activity.java:8570)
	at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1384)
	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:4150)
	... 12 more```

**Comment by F0x1d** [comment]
This "X more" are "written" by Android system, LogFox can't control it. That's just system's behavior

**Comment by r3538987** [comment]
Thanks, that's enough to know.
