### ISSUE TITLE
Crash on Navigation action/destination

### ISSUE THREAD

**Issue by shuvashish76** [F0x1d/LogFox#26]
Steps to reproduce:
1. Open LogFox > click on Settings
2. Click on any option (e.g UI)
3. Again just click on "Settings"
4. Click on back from device navigation bar
5. Again click on any option (e.g UI)
6. See error

Logs:
```
FATAL EXCEPTION: main
Process: com.f0x1d.logfox, PID: 8000
java.lang.IllegalArgumentException: Navigation action/destination com.f0x1d.logfox:id/action_settingsMenuFragment_to_settingsUIFragment cannot be found from the current destination g(com.f0x1d.logfox:id/settingsCrashesFragment) label=SettingsCrashesFragment class=com.f0x1d.logfox.ui.fragment.settings.SettingsCrashesFragment
	at z0.y.j(SourceFile:169)
	at r3.g.f(SourceFile:91)
	at androidx.preference.Preference.s(SourceFile:20)
	at e.b.onClick(SourceFile:82)
	at android.view.View.performClick(View.java:7467)
	at android.view.View.performClickInternal(View.java:7444)
	at android.view.View.access$3700(View.java:840)
	at android.view.View$PerformClick.run(View.java:28831)
	at android.os.Handler.handleCallback(Handler.java:978)
	at android.os.Handler.dispatchMessage(Handler.java:104)
	at android.os.Looper.loopOnce(Looper.java:238)
	at android.os.Looper.loop(Looper.java:357)
	at android.app.ActivityThread.main(ActivityThread.java:8090)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1026)
```
Device details:
App version: 1.3.9
Android: 12
Model: moto g71 5G

**Comment by F0x1d** [comment]
Done in 1.4.0
