### ISSUE TITLE
Feature request: add ability to record and view log files

### ISSUE THREAD

**Issue by pacjo** [F0x1d/LogFox#29]
I hope it's understandable. Since, well, long enough I used Matlog Libre. I really like your app, but it really lacks the possibility to save files and view them later, or even open log files with file picker (something even matlog lacks). Could you add this feature?

On a side note, would you consider adding amoled theme or should I open another issue for that?

**Comment by F0x1d** [comment]
There is already ability for it, isn't it? Just open "Recordings" tab. You can manage them here and export as files

**Comment by F0x1d** [comment]
BTW, isn't AMOLED theme useless?

**Comment by pacjo** [comment]
> There is already an ability for it, isn't it? Just open "Recordings" tab. You can manage them here and export as files

Ok, that's most of it, thanks. Is there an option to open any file (e.g. another log file from local storage maybe through system file picker)?

> BTW, isn't AMOLED theme useless?

In terms of battery usage? Maybe, but I like it. Implemented well it looks nice and refreshing. Whatever is the truth I just like having a choice.

**Comment by F0x1d** [comment]
> Is there an option to open any file (e.g. another log file from local storage maybe through system file picker)?

Completely didn't get it. What do you mean?

**Comment by pacjo** [comment]
I think there should be an option to do this things like this:

1. There's something like *Open other* button, you click it
2. Android's file picker (I think it's called DocumentsUI) opens up and you select the file you want to open (`.txt`, `.log`...)
3. File opens in LogFox with proper formatting, you can scroll through it, filter and do whatever you need.

Below is how Matlog does it. My file is `orca.log` captured over ADB (thus no syntax highlighting). I placed that log in the directory that matlog stores it's recordings (`/sdcard/matlog/saved_logs`), basically this skips step 2.

https://github.com/F0x1d/LogFox/assets/56438628/c362e23a-366f-41b8-aa9a-eda4c2ffd2a2

**Comment by shuvashish76** [comment]
I think what OP requested is clear.
Requested feature is "Log viewer" i.e. view already recorded logs directly through LogFox.

> There is already an ability for it, isn't it? Just open "Recordings" tab. You can manage them here and export as files.

Yes we do have that feature which is "Log manager" isn't it? ([matlog](https://github.com/plusCubed/matlog) calls it "Manage Saved Logs")

**Comment by F0x1d** [comment]
> I think what OP requested is clear.
> 
> Requested feature is "Log viewer" i.e. view already recorded logs directly through LogFox.

Yeah, i got it. I'll do it in my free time

**Comment by F0x1d** [comment]
Check out apk in https://github.com/F0x1d/LogFox/actions/runs/6365708874 to test. It will be here for 3 days. I am waiting for some feedback

**Comment by shuvashish76** [comment]
Recorded some logs > Click on any item from "Recordings" > It shows these options "Title (i.e. rename),Export/Share/Zip"
No option to view it.

Though intent works, if you open from any 3rd party application such as from a FileManager.

**Comment by F0x1d** [comment]
What about now? https://github.com/F0x1d/LogFox/actions/runs/6369691209

**Comment by shuvashish76** [comment]
Yes it works now, though I don't like the overall design of it. Needs separate issue for discussion.

**Comment by shuvashish76** [comment]
Sometimes it crashes due to delete recording > then immediately open LogFox main page.

<details><summary>Logs</summary>

<p>

```
FATAL EXCEPTION: main
Process: com.f0x1d.logfox, PID: 30224
java.io.FileNotFoundException: open failed: ENOENT (No such file or directory)
	at android.os.ParcelFileDescriptor.openInternal(ParcelFileDescriptor.java:342)
	at android.os.ParcelFileDescriptor.open(ParcelFileDescriptor.java:229)
	at androidx.core.content.FileProvider.openFile(SourceFile:92)
	at android.content.ContentProvider.openAssetFile(ContentProvider.java:2070)
	at android.content.ContentProvider.openTypedAssetFile(ContentProvider.java:2246)
	at android.content.ContentProvider.openTypedAssetFile(ContentProvider.java:2313)
	at android.content.ContentProvider$Transport.openTypedAssetFile(ContentProvider.java:551)
	at android.content.ContentResolver.openTypedAssetFileDescriptor(ContentResolver.java:2027)
	at android.content.ContentResolver.openAssetFileDescriptor(ContentResolver.java:1842)
	at android.content.ContentResolver.openInputStream(ContentResolver.java:1518)
	at w2.h.i(SourceFile:85)
	at w2.h.k(SourceFile:13)
	at c4.c.b(SourceFile:133)
	at d7.h.b(SourceFile:27)
	at d7.k.i(SourceFile:43)
	at m6.a.g(SourceFile:1)
	at kotlinx.coroutines.i0.run(Unknown Source:104)
	at kotlinx.coroutines.internal.e.run(Unknown Source:11)
	at kotlinx.coroutines.scheduling.i.run(Unknown Source:2)
	at kotlinx.coroutines.scheduling.a.run(SourceFile:77)
	Suppressed: kotlinx.coroutines.g0: [q1{Cancelling}@aa51be4, Dispatchers.Main.immediate]
```

</p>
</details>

**Comment by F0x1d** [comment]
What's wrong with design?

**Comment by pacjo** [comment]
I don't know, it looks good to me.

However scrolling seems broken, video below.

**Comment by F0x1d** [comment]
Yeah, already fixed it and some other issues. https://github.com/F0x1d/LogFox/actions/runs/6371850006

**Comment by pacjo** [comment]
> Yeah, already fixed it and some other issues. https://github.com/F0x1d/LogFox/actions/runs/6371850006

Great! This and opening log files directly from storage in LogFox works really well.
