### ISSUE TITLE
ArrayIndexOutOfBoundsException, a requent and difficult to reproduce bug

### ISSUE THREAD

**Issue by Jesse205** [F0x1d/LogFox#48]
```txt
java.lang.ArrayIndexOutOfBoundsException: length=15000; index=-1
	at java.util.ArrayList.get(ArrayList.java:439)
	at java.util.Collections$UnmodifiableList.get(Collections.java:1356)
	at com.f0x1d.logfox.ui.viewholder.base.BaseViewHolder.getCurrentItem(BaseViewHolder.kt:11)
	at com.f0x1d.logfox.ui.viewholder.LogViewHolder.expandOrCollapseItem(LogViewHolder.kt:111)
	at com.f0x1d.logfox.ui.viewholder.LogViewHolder._init_$lambda$1(LogViewHolder.kt:55)
	at com.f0x1d.logfox.ui.viewholder.LogViewHolder.$r8$lambda$wpliB5BmvfRQPqhmRmCq5TmEJzs(Unknown Source:0)
	at com.f0x1d.logfox.ui.viewholder.LogViewHolder$$ExternalSyntheticLambda1.onClick(Unknown Source:2)
	at android.view.View.performClick(View.java:7575)
	at android.view.View.performClickInternal(View.java:7548)
	at android.view.View.-$$Nest$mperformClickInternal(Unknown Source:0)
	at android.view.View$PerformClick.run(View.java:29848)
	at android.os.Handler.handleCallback(Handler.java:942)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loopOnce(Looper.java:211)
	at android.os.Looper.loop(Looper.java:300)
	at android.app.ActivityThread.main(ActivityThread.java:8294)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:580)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1028)
```
I don't know what I did, and I can't reproduce it either.

I have checked the source code and it is possible that the `RecyclerView. getBindingAdapterPosition()` method returned `NO_POSITION`

The following screenshot is an exception monitoring from MIUI.
![Screenshot_2023-10-09-05-17-52-173_com.miui.thirdappassistant.jpg](https://github.com/F0x1d/LogFox/assets/51242302/a4a9b456-84e7-404d-9041-c488e9188ac7)

**Comment by Jesse205** [comment]
I just returned to LogFox and this exception occurred again. But I repeated it several times and still haven't reproduced this problem
![Screenshot_2023-10-09-05-22-32-100_com.miui.thirdappassistant.jpg](https://github.com/F0x1d/LogFox/assets/51242302/f90e54e3-8c84-4a79-887e-97515507da74)

**Comment by F0x1d** [comment]
According to logs, there is somehow click performed on a log line without this log line being displayed?

**Comment by Jesse205** [comment]
It could be, but I can't be sure because it came out of nowhere and I forget what was going on before.

But just now, I was coming back to this page when the software crashed and the software appears to have reloaded. I may saw an empty page.

**Comment by F0x1d** [comment]
I've added a check in 69f51c3a60ed8a9a72b69154c09a5de2ecd55e5e, so there should be no more crashes
