### ISSUE TITLE
App crashing during navigation

### ISSUE THREAD

**Issue by NikunjKhangwal** [F0x1d/LogFox#81]
The app is crashing for me whenever i tap on "crashes" button in navigation bar. It was working fine a few days ago. It just started to happen randomly. There isn't any problem when i tap on a current crash directly from notification to access it.

**Here's the log:**

FATAL EXCEPTION: main
Process: com.f0x1d.logfox, PID: 12943
android.database.sqlite.SQLiteBlobTooBigException: Row too big to fit into CursorWindow requiredPos=18, totalRows=19
	at android.database.sqlite.SQLiteConnection.nativeExecuteForCursorWindow(Native Method)
	at android.database.sqlite.SQLiteConnection.executeForCursorWindow(SQLiteConnection.java:1003)
	at android.database.sqlite.SQLiteSession.executeForCursorWindow(SQLiteSession.java:838)
	at android.database.sqlite.SQLiteQuery.fillWindow(SQLiteQuery.java:62)
	at android.database.sqlite.SQLiteCursor.fillWindow(SQLiteCursor.java:153)
	at android.database.sqlite.SQLiteCursor.onMove(SQLiteCursor.java:123)
	at android.database.AbstractCursor.moveToPosition(AbstractCursor.java:255)
	at android.database.AbstractCursor.moveToNext(AbstractCursor.java:287)
	at w2.c.a(SourceFile:555)
	at w2.c.call(SourceFile:182)
	at j1.c.n(SourceFile:85)
	at b7.a.m(SourceFile:1)
	at q7.i0.run(SourceFile:1)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:644)
	at java.lang.Thread.run(Thread.java:1012)
	Suppressed: v7.g: [p1{Cancelling}@b13b5ac, Dispatchers.Main.immediate]

**Comment by F0x1d** [comment]
This is because of a bad mechanism of storing dump logs in older version of LogFox. You can just clear your crashes to solve the problem (or LogFox data if you can't enter Crashes screen) and use the latest version

**Comment by NikunjKhangwal** [comment]
I was on the latest version already so clearing the data fixed it. Thanks
