### ISSUE TITLE
[Bug] Double clicking on the recording item will cause it to crash

### ISSUE THREAD

**Issue by Jesse205** [F0x1d/LogFox#98]
https://github.com/F0x1d/LogFox/assets/51242302/e24b642e-9216-4b39-9c37-f9321b6f402e

```txt
FATAL EXCEPTION: main
Process: com.f0x1d.logfox, PID: 31710
java.lang.IllegalArgumentException: Navigation action/destination com.f0x1d.logfox:id/action_recordingsFragment_to_recordingBottomSheet cannot be found from the current destination b(com.f0x1d.logfox:id/recordingBottomSheet) label=RecordingBottomSheet
	at f1.v.l(SourceFile:131)
	at f1.v.n(SourceFile:1)
	at y3.d.n(SourceFile:292)
	at h4.i.onClick(SourceFile:54)
	at android.view.View.performClick(View.java:7322)
	at android.view.View.performClickInternal(View.java:7296)
	at android.view.View.access$3600(View.java:839)
	at android.view.View$PerformClick.run(View.java:28319)
	at android.os.Handler.handleCallback(Handler.java:900)
	at android.os.Handler.dispatchMessage(Handler.java:103)
	at android.os.Looper.loop(Looper.java:219)
	at android.app.ActivityThread.main(ActivityThread.java:8673)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:513)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1109)
```

**Comment by F0x1d** [comment]
Fixed in 3dcc5a1e451586ecb5d199ae5b4493c753929815
